apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ibm-mq-promote-stage-prod
  annotations:
    app.openshift.io/runtime: test
spec:
  params:
    - name: git-url
      description: The url for the git repository
    - name: git-revision
      description: git branch for the test app
      default: master
    - name: src-environment
      description: environment
      default: staging
    - name: dest-environment
      description: environment
      default: prod
    - name: app-path
      description: Path in gitops repo
      default: mq/environments
    - name: git-pr
      description: Enable the pipeline to do a PR for the gitops repo
      default: "true"
    - name: test-plan
      description: Path of the postman collection
      default: "jmeter/mq-spring-app.jmx"
  tasks:
    - name: stage-instance-tests
      taskRef:
        name: ibm-jmeter-performance-test
      params:
        - name: git-url
          value: "$(params.git-url)"
        - name: src-environment
          value: "$(params.src-environment)"
        - name: test-plan
          value: "$(params.test-plan)"
    - name: gitops
      taskRef:
        name: ibm-gitops
      runAfter:
        - stage-instance-tests
      params:
        - name: app-name
          value: "$(tasks.stage-instance-tests.results.app-name)"
        - name: src-environment
          value: "$(params.src-environment)"
        - name: dest-environment
          value: "$(params.dest-environment)"
        - name: app-path
          value: "$(params.app-path)"
        - name: git-pr
          value: "$(params.git-pr)"
